[package]
name = "dlob-builder"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
drift-rs = { path = "../../../drift-rs", features = ["unsafe_pub"] }
solana-commitment-config = "2"
solana-keypair= "2"
tokio = "*"
